"""Registry of the only local tools an agent is allowed to request.

The registry is a security boundary: tool identifiers are resolved from this
fixed mapping, never from dynamic imports, globals, eval, or arbitrary code.
"""

from dataclasses import dataclass
from typing import Literal

from pydantic import BaseModel

from app.tools.schemas import CalculatorInput, DocumentIdInput, KnowledgeSearchInput

ToolPermission = Literal["READ_ONLY", "COMPUTE_ONLY"]


@dataclass(frozen=True)
class ToolDefinition:
    """Describe one approved local capability and its execution policy.

    The registry definition is metadata, not a dynamically callable object.
    ``ToolExecutor`` owns the explicit mapping from an approved ID to its
    implementation, which keeps the execution surface auditable.
    """

    id: str
    name: str
    description: str
    schema: type[BaseModel]
    permission: ToolPermission = "READ_ONLY"
    enabled: bool = True


TOOLS: dict[str, ToolDefinition] = {
    "knowledge_search": ToolDefinition(
        "knowledge_search",
        "Search Local Knowledge Base",
        "Search indexed local documents.",
        KnowledgeSearchInput,
    ),
    "document_metadata": ToolDefinition(
        "document_metadata",
        "Document Metadata",
        "Read known document metadata.",
        DocumentIdInput,
    ),
    "document_text": ToolDefinition(
        "document_text",
        "Document Text",
        "Read bounded extracted text.",
        DocumentIdInput,
    ),
    "calculator": ToolDefinition(
        "calculator",
        "Calculator",
        "Safe deterministic arithmetic.",
        CalculatorInput,
        "COMPUTE_ONLY",
    ),
}


def get_tool(tool_id: str) -> ToolDefinition:
    """Return a registered definition or raise ``KeyError`` for an unknown ID.

    Args:
        tool_id: Identifier generated by an agent controller or API client.

    Returns:
        The approved local tool definition for the supplied ID.
    """
    # SECURITY: this fixed mapping forbids eval, exec, shell execution,
    # dynamic imports, and dynamic function resolution from LLM output.
    return TOOLS[tool_id]
