"""Registry of the only local tools an agent is allowed to request.

The registry is a security boundary: tool identifiers are resolved from this
fixed mapping, never from dynamic imports, globals, eval, or arbitrary code.
"""

from dataclasses import dataclass
from typing import Literal

from pydantic import BaseModel

from app.tools.schemas import CalculatorInput, DataSourcesInput, DocumentIdInput, KnowledgeSearchInput, SandboxCodeInput
from app.schemas.analysis import DataAnalysisRequest
from app.schemas.deliverables import ChartSpec, DocumentSpec, TableSpec

ToolPermission = Literal["READ_ONLY", "COMPUTE_ONLY"]


@dataclass(frozen=True)
class ToolDefinition:
    """Describe one approved local capability and its execution policy.

    The registry definition is metadata, not a dynamically callable object.
    ``ToolExecutor`` owns the explicit mapping from an approved ID to its
    implementation, which keeps the execution surface auditable.
    """

    id: str
    name: str
    description: str
    schema: type[BaseModel]
    permission: ToolPermission = "READ_ONLY"
    enabled: bool = True


TOOLS: dict[str, ToolDefinition] = {
    "knowledge_search": ToolDefinition(
        "knowledge_search",
        "Search Local Knowledge Base",
        "Search indexed local documents.",
        KnowledgeSearchInput,
    ),
    "document_metadata": ToolDefinition(
        "document_metadata",
        "Document Metadata",
        "Read known document metadata.",
        DocumentIdInput,
    ),
    "document_text": ToolDefinition(
        "document_text",
        "Document Text",
        "Read bounded extracted text.",
        DocumentIdInput,
    ),
    "list_data_sources": ToolDefinition(
        "list_data_sources",
        "List Local Data Sources",
        "List managed CSV and XLSX sources with their available columns.",
        DataSourcesInput,
    ),
    "calculator": ToolDefinition(
        "calculator",
        "Calculator",
        "Safe deterministic arithmetic.",
        CalculatorInput,
        "COMPUTE_ONLY",
    ),
    "python_sandbox": ToolDefinition("python_sandbox", "Safe Python Sandbox", "Run bounded Python; no shell or host paths.", SandboxCodeInput, "COMPUTE_ONLY"),
    "data_analysis": ToolDefinition("data_analysis", "Analyze Local Data", "Analyze a managed CSV or XLSX artifact/document.", DataAnalysisRequest, "COMPUTE_ONLY"),
    "create_chart": ToolDefinition("create_chart", "Create Local Chart", "Generate a validated chart from structured rows.", ChartSpec, "COMPUTE_ONLY"),
    "create_spreadsheet": ToolDefinition("create_spreadsheet", "Create Spreadsheet", "Generate a validated XLSX from structured rows.", TableSpec, "COMPUTE_ONLY"),
    "create_document": ToolDefinition("create_document", "Create Document", "Generate a validated DOCX report from structured content.", DocumentSpec, "COMPUTE_ONLY"),
    "create_presentation": ToolDefinition("create_presentation", "Create Presentation", "Generate a validated PPTX summary from structured rows.", TableSpec, "COMPUTE_ONLY"),
    "create_pdf": ToolDefinition("create_pdf", "Create PDF", "Generate a validated PDF summary from structured rows.", TableSpec, "COMPUTE_ONLY"),
}


def get_tool(tool_id: str) -> ToolDefinition:
    """Return a registered definition or raise ``KeyError`` for an unknown ID.

    Args:
        tool_id: Identifier generated by an agent controller or API client.

    Returns:
        The approved local tool definition for the supplied ID.
    """
    # SECURITY: this fixed mapping forbids eval, exec, shell execution,
    # dynamic imports, and dynamic function resolution from LLM output.
    return TOOLS[tool_id]
